apiVersion: batch/v1
kind: Job
metadata:
  name: rhub-snapshot-{{ .Values.snapshotId }}
spec:
  template:
    spec:
      containers:
      - name: rhub-snapshot-{{ .Values.snapshotId }}
        image: curlimages/curl:7.76.1
        imagePullPolicy: IfNotPresent
        command: ["curl",  "gmbadges-restorehub.gm.svc.cluster.local:30900/snapshots", "--data", '{"ID":{{ .Values.snapshotId }}, "Name":{{ .Values.repoName }}']
      restartPolicy: Never
  backoffLimit: 50

# spec:
#  repoName: {{ .Values.repoName }}
#  snapshotName: {{ .Values.snapshotName }}
#  snapshotId: {{ .Values.snapshotId }}
