apiVersion: batch/v1
kind: Job
metadata:
  name: rhub-snapshot-{{ .Values.snapshotId }}
spec:
  template:
    spec:
      containers:
      - name: rhub-snapshot-{{ .Values.snapshotId }}
        image: restorehub/k8sconnector:v0.4
        imagePullPolicy: IfNotPresent
        command: ["./connector",  "snapshot", "{{ .Values.snapshotId }}"]
      restartPolicy: Never
  backoffLimit: 50

# spec:
#  repoName: {{ .Values.repoName }}
#  snapshotName: {{ .Values.snapshotName }}
#  snapshotId: {{ .Values.snapshotId }}
